### ISSUE TITLE
Just saying hi

### ISSUE THREAD

**Issue by gavmck** [mverissimo/storybook-addon-status#1]
Hey there!

Just interested why the new version of `storybook-addon-status` rather than making a PR against the original `@etchteam/storybook-addon-status`?

Thanks!
Gav

**Comment by mverissimo** [comment]
Hi @gavmck, 

I think don't have any specific reason, I was only practicing how to create an addon and decided to create this one, my apologies if this affects your work somehow, I did some research and find similar packages:

[Storybook Addon Badges](https://storybook.js.org/addons/@geometricpanda/storybook-addon-badges)
[Status](https://storybook.js.org/addons/@etchteam/storybook-addon-status) your package

And I agree with you about making a pull request against it, but we have different purposes.


Tks!

**Comment by gavmck** [comment]
All good I was only curious :)

Have a great Tuesday!
